CREATE DATABASE IF NOT EXISTS Shortify;
USE Shortify;

CREATE TABLE IF NOT EXISTS links(
    id INT AUTO_INCREMENT PRIMARY KEY,
    original_link TEXT NOT NULL,
    clicks INT DEFAULT 0,
    last_access TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    isDeleted BOOLEAN DEFAULT FALSE NOT NULL
) AUTO_INCREMENT=1234567890;